version: "3"
services:
  pyspark:
    image: "jupyter/pyspark-notebook:spark-3.3.2"
    working_dir: /home/app/
    volumes:
      - /home/tiao/EDKS-0003-APACHE-SPARK-PARA-ENGENHARIA-DE-DADOS-KICKSTART/app/:/home/app/
    ports:
      - 8888:8888
    depends_on:
      - postgres
    networks:
      - minha-rede-master

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: data-way-poc
      POSTGRES_USER: admin-dataway
      POSTGRES_PASSWORD: IloveDataway
    ports:
      - "5432:5432"
    networks:
      - minha-rede-master

networks:
  minha-rede-master:
